# Generated by Django 3.2 on 2021-04-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210429_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='authorized_user',
        ),
    ]
