# Generated by Django 3.2 on 2021-04-30 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_remove_login_authorized_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='authorized_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
